# Generated by Django 4.2.16 on 2024-12-04 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_aircraft_parts_remove_part_description_team_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='team',
            name='members',
        ),
        migrations.AddField(
            model_name='aircraft',
            name='parts',
            field=models.ManyToManyField(through='myapp.AircraftPart', to='myapp.part'),
        ),
        migrations.CreateModel(
            name='TeamPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.part')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.team')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.IntegerField()),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.part')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='parts',
            field=models.ManyToManyField(through='myapp.ProductPart', to='myapp.part'),
        ),
    ]
