# Generated by Django 4.2.16 on 2024-12-04 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_product_remove_team_members_aircraft_parts_teampart_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aircraft',
            name='parts',
        ),
        migrations.AddField(
            model_name='aircraft',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='type',
            field=models.CharField(choices=[('TB2', 'TB2'), ('TB3', 'TB3'), ('AKINCI', 'AKINCI'), ('KIZILELMA', 'KIZILELMA')], default=5, max_length=100),
            preserve_default=False,
        ),
    ]
